name: superstore_dbt
version: 1.0.0
config-version: 2

profile: superstore_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  superstore_dbt:
    core:
      +materialized: table
    marts:
      +materialized: table
