superstore_dbt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      port: 8123
      schema: superstore_db
      database: superstore_db
      threads: 4
      host: clickhouse
      user: default
      secure: false
