FROM apache/airflow:3.1.0
WORKDIR /opt/airflow


RUN pip install --no-cache-dir poetry==2.2.1
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock* ./
RUN poetry install --without dev --no-interaction --no-ansi --no-root